pid:
  kp: 5.0
  ki: 0.1
  kd: 0.4

speed:
  v_min: 0.03    # minimum forward speed [m/s] 0.03
  v_max: 0.06    # maximum forward speed [m/s] 0.15 (0.08 for paletting)

limits:
  omega_max: 0.5 # max absolute angular speed [rad/s]

image:
  width: 640.0   # image width in pixels (update if your camera is different)
